### ISSUE TITLE
UI is very slow with a larger cluster

### ISSUE THREAD

**Issue by idrennanvmware** [hashicorp/consul#11580]
#### Overview of the Issue

The UI for consul is unusable on one of our larger clusters.  It's a 53 node cluster with 273 services and the UI doesn't render properly and is unresponsive when viewing any of the sections (Nodes, Services, KV, or Intentions)

API calls are very responsive though and this seems limited to the UI

### Consul info for both Client and Server
Consul 1.10.3

**Comment by idrennanvmware** [comment]
Additional information

Chrome seems fine but Safari is not happy

**Comment by johncowen** [comment]
Hi @idrennanvmware 

Is this something you've noticed that is different from an older version of the UI, for example was it any more responsive previous to upgrading to 1.10.3?

Thanks,

**Comment by idrennanvmware** [comment]
@johncowen  I can't say for sure as this is our first large cluster so we don't have anything to compare back against from older versions

**Comment by johncowen** [comment]
Np, thanks for report. 👀

**Comment by johncowen** [comment]
Hi @idrennanvmware 

I just gave our latest 1.10 a run in the UI with 1000 services and 1000 nodes and I didn't see any slow down in performance in either Chrome or Safari. I'm wondering if your cluster is very noisy (i.e. lots of changes in a short space of time), and therefore blocking queries are almost permanently streaming to the UI and possibly causing a performance issue in the UI that I'm not seeing. If you could let me know if you have lots of changes over a short space of time that would be great.

Also, you could try turning off our blocking query support in the UI via the UIs settings page and seeing if that has any impact on things. Let me know if that affects things at all.

Lastly, could you let me know versions of things you are trying in (so Chrome and Safari versions)

Let me know, and we can continue to investigate to figure out what this could be.

Thanks,

**Comment by idrennanvmware** [comment]
@johncowen  thanks for looking in to this.   Yes, actually, we had a number of nodes flapping at the time due to raft issues (fw rule preventing some traffic between certain nodes) so there were approx 15 nodes or so going in and out of the catalog repeatedly  - actually the reason we were in the UI in the first place.

As of this morning this doesn't seem to be an issue anymore (ui speed) but it's good to know the blocking queries could be the problem and we can disable that if need be in these scenarios.   It does create a little challenge in visualizing flapping systems though if we have to turn that off.

Thanks!
Ian

**Comment by johncowen** [comment]
Oh awesome! (well kind of 😆 ). Good to hear that setting is useful sometimes (even if it is very occasionally!)

I had line of work a while ago addressing the problem when we have almost permanently streaming data from the backend. I was calculating the delta of changes off of the main UI thread, which meant the UI itself remained responsive even with very noisy clusters. Does that sounds like something you'd find beneficial in this case?

**Comment by johncowen** [comment]
I'm going to close this issue as I 'think' that the main specific issue here is resolved - aside from that we are always looking for ways to improve performance and this is always actively being looked at.

**Comment by 2022liuws** [comment]
The problem is still there，80000 service ，1000 nodes， consul version 1.13.1 ，when I  access to   http://127.0.0.1:8500/ui/monitor/services.  very slowly
