### ISSUE TITLE
consul reload deregistering services

### ISSUE THREAD

**Issue by wuub** [hashicorp/consul#1173]
I'm encountering  a strange case when using **consul reload**.

 Sometimes it does what I would expect 

```
2015/08/13 13:53:14 [INFO] agent.rpc: Accepted client: 127.0.0.1:46004
2015/08/13 13:53:15 [INFO] agent: Synced service 'nhsyslog'
2015/08/13 13:53:15 [INFO] agent: Synced service 'rsyslog'
2015/08/13 13:53:16 [INFO] agent: Synced service 'test-check'
2015/08/13 13:53:17 [INFO] agent: Synced service 'consul-dns'
2015/08/13 13:53:17 [INFO] agent: Synced service 'consul-template'
2015/08/13 13:53:18 [INFO] agent: Synced service 'journal-gateway'
2015/08/13 13:53:19 [INFO] agent: Synced service 'importer'
```

and a while (30s, no changes to service definitions) later the same call to **consul reload** has super-scary side effect of, de-registering and re-registering all services and check on a machine.

```
2015/08/13 13:53:55 [INFO] agent.rpc: Accepted client: 127.0.0.1:46012
2015/08/13 13:53:56 [INFO] agent: Deregistered service 'nhsyslog'
2015/08/13 13:53:56 [INFO] agent: Deregistered service 'rsyslog'
2015/08/13 13:53:57 [INFO] agent: Deregistered service 'test-check'
2015/08/13 13:53:58 [INFO] agent: Synced service 'consul-dns'
2015/08/13 13:53:58 [INFO] agent: Synced service 'consul-template'
2015/08/13 13:53:59 [INFO] agent: Synced service 'journal-gateway'
2015/08/13 13:54:00 [INFO] agent: Synced service 'importer'
2015/08/13 13:54:00 [INFO] agent: Deregistered check 'service:nhsyslog'
2015/08/13 13:54:01 [INFO] agent: Deregistered check 'service:rsyslog'
2015/08/13 13:54:01 [INFO] agent: Deregistered check 'service:test-check'
2015/08/13 13:54:02 [INFO] agent: Synced service 'nhsyslog'
2015/08/13 13:54:03 [INFO] agent: Synced service 'rsyslog'
2015/08/13 13:54:03 [INFO] agent: Synced service 'test-check'
2015/08/13 13:54:04 [INFO] agent: Synced check 'service:consul-dns'
2015/08/13 13:54:04 [INFO] agent: Synced check 'service:consul-template'
2015/08/13 13:54:05 [INFO] agent: Synced check 'service:journal-gateway'
2015/08/13 13:54:05 [INFO] agent: Synced check 'service:importer'
2015/08/13 13:54:50 [WARN] agent: Check 'service:consul-template' is now critical
2015/08/13 13:54:51 [INFO] agent: Synced check 'service:consul-template'
```

Do you know what can be causing this?

**Comment by slackpad** [comment]
I wonder if a sync from the server is somehow getting in during the reload (it looks like the code is set up to prevent that). Can you see if you can reproduce this with the log level set to debug so we can see what's happening in more detail?

**Comment by wuub** [comment]
Sure. I forgot to mention, that this is on consul-0.5.1 since we didn't have time to upgrade yet.

Full (a bit anonymized) log is here: https://gist.github.com/wuub/e91bb1db85caef928f03
All log lines are there. Wall of http requests is from consul-template.  

Log covers 3 consul reloads. I'm pretty sure the second one started service de-registering.

**Comment by slackpad** [comment]
Thanks for the logs, unfortunately I don't see anything definitive in there.

Looking through the code again it seems like the server sync isn't fully protected during a reload. It looks like in `local.go/antiEntropy()` it doesn't respect the paused state, so it can go inside of `setSyncState()` at that same time the `handleReload()` function is running. Also, `handleReload()` doesn't take the lock at the top, it locks the data structures as it goes along. It seems, though I haven't confirmed, that `handleReload()` starts processing, and then a server sync happens via `setSyncState` and twiddles the data structures that are being reloaded.

I'll have to work to repro this, but I bet this is it.

**Comment by wuub** [comment]
I can help with repo if necessary.
Run a different version on one of the nodes, with more verbose logging.

**Comment by slackpad** [comment]
@wuub thanks that would be great! Just for science can you run 0.5.2 on another node just to make sure I'm not missing anything and it shows the problem, too? Then I'll give you a patch (or patched build if you like) of 0.5.2 that locks out the server updates during the pause for a reload. Running 0.5.2 along with other 0.5.1 nodes should not be a problem.

**Comment by wuub** [comment]
@slackpad we are now on 0.5.2, I'll try to confirm that the problem still occurs ASAP.

I'll can build a debug binary myself, just point me to a commit/branch :)

**Comment by wuub** [comment]
Yup, consul 0.5.2 on all servers, consul 0.5.2 on the client node, two `consul reloads` in quick succession trigger the problem. Each time, every time :)

**Comment by slackpad** [comment]
Thanks for checking that! I pushed up a branch with a possible fix here:

https://github.com/hashicorp/consul/tree/v0.5.2-reload-patches

This has a few other changes that should be unrelated: some bugfixes, some cherry picks from master to get Consul to build and run with the latest version of the dependencies, and some little things like fixes to expired certs in unit tests.

**Comment by slackpad** [comment]
Sorry I forgot the note above - you'll definitely want to sync memberlist and serf back to the hashes listed above. Let me know if you have any trouble building it.

**Comment by wuub** [comment]
I only had a few minutes to test it today and will continue on Monday. But  initial run seems to suggest that it did not fix service deregistering.

**Comment by wuub** [comment]
@slackpad sorry for the delay, but I finally have something meaningful to report.

Our consul is started with `-config-dir=/etc/consul` and there are two kind of jsons there:
`service-[name].json` (with persistens service configs) and `default.json` (with consul config, your typical acl_ttl, domain, "dns", recursors and so on)... and a 

**"start_join": [list, of, our, consul, server, IPs]**

If and only IF it's there, almost every consul reload triggers service deregistering and/or checks syncs.  When I remove start_join I am **unable** to recreate deregistration problem.

**Comment by wuub** [comment]
Some other findings, I've added PrintStack() to the only place that prints
```go
// deleteService is used to delete a service from the server
func (l *localState) deleteService(id string) error {
        if id == "" {
                return fmt.Errorf("ServiceID missing")
        }

        req := structs.DeregisterRequest{
                Datacenter:   l.config.Datacenter,
                Node:         l.config.NodeName,
                ServiceID:    id,
                WriteRequest: structs.WriteRequest{Token: l.serviceToken(id)},
        }
        var out struct{}
        err := l.iface.RPC("Catalog.Deregister", &req, &out)
        if err == nil {
                delete(l.serviceStatus, id)
                debug.PrintStack()
                l.logger.Printf("[INFO] agent: Deregistered service '%s'", id)
        }
        return err
}
```

```
wrz 11 15:29:27 demo-8 consul[2345]: /home/wuub/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/consul/command/agent/local.go:504 (0x4c14c0)
wrz 11 15:29:27 demo-8 consul[2345]: /home/wuub/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/consul/command/agent/local.go:453 (0x4c0bfb)
wrz 11 15:29:27 demo-8 consul[2345]: /home/wuub/.gvm/pkgsets/go1.4.2/global/src/github.com/hashicorp/consul/command/agent/local.go:331 (0x4bf81b)
wrz 11 15:29:27 demo-8 consul[2345]: /home/wuub/.gvm/gos/go1.4.2/src/runtime/asm_amd64.s:2232 (0x450b11)
wrz 11 15:29:27 demo-8 consul[2345]: 2015/09/11 15:29:27 [INFO] agent: Deregistered service 'test-check4'
```

which suggest l.antiEntropy() -> l.syncChanges() -> l.deleteService(id)

**Comment by wuub** [comment]
I'm pretty sure it's a problem with unexpected `ResumeSync()` called by Agent.AddService() during `(c *Command) handleReload(config *Config)` that allow `antiEntropy()` while reload is still in progress. 

I'll report more in a moment.

**Comment by wuub** [comment]
Yup, I'm pretty sure this is it:

After adding some logging to syncChanges(), PauseSync(), ResumeSync() and hanldeReload() I was able to get following log.  Which clearly shows, that syncChanges() manages to strart during configuration reload. 

```go
func (l *localState) syncChanges() error {
	l.Lock()
	defer l.Unlock()

	// Bail out if we are paused. We protect the pause status with the lock
	// so that we finish in here before pausing takes effect.
	if l.isPaused() {
		return nil
	}

	l.logger.Print("[WARN] syncChanges()")
        ...
```
```go
// PauseSync is used to pause anti-entropy while bulk changes are make
func (a *Agent) PauseSync() {
	a.logger.Println("[INFO] agent: PauseSync()")
	a.state.Pause()
}

// ResumeSync is used to unpause anti-entropy after bulk changes are make
func (a *Agent) ResumeSync() {
	a.logger.Println("[INFO] agent: ResumeSync()")
	a.state.Resume()
}
````
```go
// handleReload is invoked when we should reload our configs, e.g. SIGHUP
func (c *Command) handleReload(config *Config) *Config {
	c.Ui.Output("Reloading configuration...")
	newConf := c.readConfig()
	if newConf == nil {
		c.Ui.Error(fmt.Sprintf("Failed to reload configs"))
		return config
	}

	// Change the log level
	minLevel := logutils.LogLevel(strings.ToUpper(newConf.LogLevel))
	if ValidateLevelFilter(minLevel, c.logFilter) {
		c.logFilter.SetMinLevel(minLevel)
	} else {
		c.Ui.Error(fmt.Sprintf(
			"Invalid log level: %s. Valid log levels are: %v",
			minLevel, c.logFilter.Levels))

		// Keep the current log level
		newConf.LogLevel = config.LogLevel
	}

	// Bulk update the services and checks
	c.agent.PauseSync()
	defer c.agent.ResumeSync()

	// Snapshot the current state, and restore it afterwards
	snap := c.agent.snapshotCheckState()
	defer c.agent.restoreCheckState(snap)

	// First unload all checks and services. This lets us begin the reload
	// with a clean slate.
	c.Ui.Error("Unloading services")
	if err := c.agent.unloadServices(); err != nil {
		c.Ui.Error(fmt.Sprintf("Failed unloading services: %s", err))
		return nil
	}
	c.Ui.Error("Unloading checks")
	if err := c.agent.unloadChecks(); err != nil {
		c.Ui.Error(fmt.Sprintf("Failed unloading checks: %s", err))
		return nil
	}

	// Reload services and check definitions.
	c.Ui.Error("Loading services")
	if err := c.agent.loadServices(newConf); err != nil {
		c.Ui.Error(fmt.Sprintf("Failed reloading services: %s", err))
		return nil
	}
	c.Ui.Error("Loading checks")
	if err := c.agent.loadChecks(newConf); err != nil {
		c.Ui.Error(fmt.Sprintf("Failed reloading checks: %s", err))
		return nil
	}

	// Get the new client listener addr
	httpAddr, err := newConf.ClientListener(config.Addresses.HTTP, config.Ports.HTTP)
	if err != nil {
		c.Ui.Error(fmt.Sprintf("Failed to determine HTTP address: %v", err))
	}

	// Deregister the old watches
	for _, wp := range config.WatchPlans {
		wp.Stop()
	}

	// Register the new watches
	for _, wp := range newConf.WatchPlans {
		go func(wp *watch.WatchPlan) {
			wp.Handler = makeWatchHandler(c.logOutput, wp.Exempt["handler"])
			wp.LogOutput = c.logOutput
			if err := wp.Run(httpAddr.String()); err != nil {
				c.Ui.Error(fmt.Sprintf("Error running watch: %v", err))
			}
		}(wp)
	}

	c.Ui.Output("DONE Reloading configuration")

	return newConf
}
```

```
wrz 11 16:57:25 d8 consul[4998]: 2015/09/11 16:57:25 [WARN] memberlist: Refuting a suspect message (from: d8)
wrz 11 16:57:25 d8 consul[4998]: 2015/09/11 16:57:25 [WARN] syncChanges()
wrz 11 16:57:27 d8 consul[4998]: 2015/09/11 16:57:27 [INFO] agent.rpc: Accepted client: 127.0.0.1:52385
wrz 11 16:57:27 d8 consul[4998]: ==> Caught signal: hangup
wrz 11 16:57:27 d8 consul[4998]: ==> Reloading configuration...
wrz 11 16:57:27 d8 consul[4998]: 2015/09/11 16:57:27 [INFO] agent: PauseSync()
wrz 11 16:57:27 d8 consul[4998]: ==> Unloading services
wrz 11 16:57:27 d8 consul[4998]: ==> Unloading checks
wrz 11 16:57:27 d8 consul[4998]: ==> Loading services
wrz 11 16:57:27 d8 consul[4998]: 2015/09/11 16:57:27 [INFO] agent: PauseSync()
wrz 11 16:57:27 d8 consul[4998]: 2015/09/11 16:57:27 [INFO] agent: ResumeSync()
wrz 11 16:57:27 d8 consul[4998]: 2015/09/11 16:57:27 [INFO] agent: PauseSync()
wrz 11 16:57:27 d8 consul[4998]: 2015/09/11 16:57:27 [WARN] syncChanges()  <<<<<<<<<<<<<<<<< THIS >>>>>>>>>>>>>>>>>>>>>
wrz 11 16:57:28 d8 consul[4998]: 2015/09/11 16:57:28 [INFO] agent: Deregistered service 'test-check2'
wrz 11 16:57:29 d8 consul[4998]: 2015/09/11 16:57:29 [INFO] agent: Deregistered service 'test-check3'
wrz 11 16:57:29 d8 consul[4998]: 2015/09/11 16:57:29 [INFO] agent: Deregistered service 'test-check4'
wrz 11 16:57:30 d8 consul[4998]: 2015/09/11 16:57:30 [INFO] agent: Synced service 'test-check'
wrz 11 16:57:31 d8 consul[4998]: 2015/09/11 16:57:31 [INFO] agent: Deregistered service 'test-check1'
wrz 11 16:57:31 d8 consul[4998]: 2015/09/11 16:57:31 [INFO] agent: ResumeSync()
wrz 11 16:57:31 d8 consul[4998]: 2015/09/11 16:57:31 [WARN] syncChanges()
wrz 11 16:57:31 d8 consul[4998]: 2015/09/11 16:57:31 [INFO] agent: PauseSync()
wrz 11 16:57:33 d8 consul[4998]: 2015/09/11 16:57:33 [INFO] agent: Synced service 'test-check1'
wrz 11 16:57:33 d8 consul[4998]: 2015/09/11 16:57:33 [INFO] agent: ResumeSync()
wrz 11 16:57:33 d8 consul[4998]: 2015/09/11 16:57:33 [WARN] syncChanges()
wrz 11 16:57:33 d8 consul[4998]: 2015/09/11 16:57:33 [INFO] agent: PauseSync()
wrz 11 16:57:34 d8 consul[4998]: 2015/09/11 16:57:34 [INFO] agent: Synced service 'test-check2'
wrz 11 16:57:34 d8 consul[4998]: 2015/09/11 16:57:34 [INFO] agent: ResumeSync()
wrz 11 16:57:34 d8 consul[4998]: 2015/09/11 16:57:34 [INFO] agent: PauseSync()
wrz 11 16:57:34 d8 consul[4998]: 2015/09/11 16:57:34 [WARN] syncChanges()
wrz 11 16:57:35 d8 consul[4998]: 2015/09/11 16:57:35 [INFO] agent: Synced service 'test-check3'
wrz 11 16:57:35 d8 consul[4998]: 2015/09/11 16:57:35 [INFO] agent: ResumeSync()
wrz 11 16:57:35 d8 consul[4998]: ==> Loading checks
wrz 11 16:57:35 d8 consul[4998]: 2015/09/11 16:57:35 [WARN] syncChanges()==> DONE Reloading configuration  ```



Without touching other parts of code I was able to "fix" this, by making isPaused more like a semaphore.  
 
```go
func (l *localState) Pause() {
	atomic.AddInt32(&l.paused, 1)
}
func (l *localState) Resume() {
	atomic.AddInt32(&l.paused, -1)
	l.changeMade()
}
// 
func (l *localState) isPaused() bool {
	return atomic.LoadInt32(&l.paused) > 0
}
```

**Comment by ryanuber** [comment]
Hmm this is interesting - so it's basically looking like sending another HUP before the first reload is done triggers this behavior. I think we could also guard this by using a `sync.Mutex` in `handleSignals` so we can be sure we only process one at a time. It seems a bit chaotic to have two config reloads going at the same time. Thanks for all the detailed information @wuub! I'm marking this as a bug, and I think the fix should be pretty simple. We'll get this in for 0.6's release!

**Comment by wuub** [comment]
@ryanbreen two config reloads should be guarded against as well, but during the investigation I did today I was able to trigger deregistration even with a single, well behaved SIGHUP. 

I'm pretty confident that I got to the bottom of this, and AFAICT #1235 fixes the root cause of the problem we are experiencing.

**Comment by slackpad** [comment]
Thanks for nailing this down @wuub - nice work! I'll take a look over your PR, and I'll double check my original patch to see if there's anything in there worth saving since that never made it to master.

**Comment by wuub** [comment]
Thans for your help guys :+1: I think this can be closed now
