### ISSUE TITLE
Document link not working  Documents:

### ISSUE THREAD

**Issue by wushu037** [hashicorp/consul#17814]
"Health" API：https://developer.hashicorp.com/consul/api-docs/health#list-service-instances-for-service
> 1some query parameters will use the[streaming backend](https://developer.hashicorp.com/api/features/blocking#streaming-backend)

Invalid links：[streaming backend](https://developer.hashicorp.com/api/features/blocking#streaming-backend)

**Comment by david-yu** [comment]
This should be fixed. Thank you for reporting!

**Comment by wushu037** [comment]
hi, @david-yu 
Has it been solved, please?
- The link is still not working.
- #17839 pr is closed and no valid content is submitted.

**Comment by david-yu** [comment]
Sorry about that I looked a the wrong section, here is the PR to fix this: https://github.com/hashicorp/consul/pull/17958
