### ISSUE TITLE
Coodinate Datacenters Call Only Returns Local Datacenter

### ISSUE THREAD

**Issue by eneuhauser** [hashicorp/consul#3628]
### Consul Version
1.0.0

### Operating system and Environment details
Running locally on OS X 10.12.6 using two Container Linux by CoreOS stable (1409.7.0) boxes within Vagrant to simulate two datacenters.

### Description of the Issue (and unexpected/desired result)
Attempting to upgrade from Consul 0.7.5 to Consul 1.0.0. I had been using the coordinate datacenters call (`/v1/coordinate/datacenters`) to fetch the list of datacenters. In this call, Consul 0.7.5 returns all datacenters, but Consul 1.0.0 is only returning the local datacenter. I'm able to switch to the catalog datacenters call (`/v1/catalog/datacenters`) for my case, but the inconsistency could cause other issues.

### Reproduction steps
1. Launch two Consul datacenters.
2. Make `GET` request to `{{dc1}}/v1/coordinate/datacenters` and note only first datacenter is returned.
3. Make `GET` request to `{{dc2}}/v1/coordinate/datacenters` and note only second datacenter is returned.
4. Make `GET` request to `{{dc1}}/v1/catalog/datacenters` and note two datacenters are returned (the datacenters have discovered each other).

**Comment by slackpad** [comment]
Hi @eneuhauser I wasn't able to reproduce this with the latest version of Consul. We made some updates to the coordinate subsystem after 1.0.0, so it's possible this was fixed as part of that (there were some issues with negative ping times getting filtered out that _could_ be related). Can you reproduce this with Consul 1.0.2?

**Comment by eneuhauser** [comment]
Hi @slackpad, thanks for looking into this. I pulled down the 1.0.2 and still get the same results. When I make a call to `{{dc1}}/v1/coordinate/datacenters`, I'm still only getting the local datacenter and calling `{dc1}}/v1/catalog/datacenter` does return both datacenters.

Given you don't get the same results, there could be something wrong on my side although `/v1/catalog/datacenter` does return both datacenters.

As I said, I have a workaround, I was just concerned about unintended consequences.

**Comment by slackpad** [comment]
Thanks for trying it with the latest. Is it possible you only have TCP connectivity between your datacenters on 8302? Things would kind of work because of the fall-back pings but I don't think you'd get any coordinate updates (there would be warnings in the logs though). Are there any coordinate-related errors in the logs?

**Comment by eneuhauser** [comment]
Yeah, it looks like an error on my end, here's an excerpt from my logs:

```
BootstrapExpect is set to 1; this is the same as Bootstrap mode.
bootstrap = true: do not enable unless necessary
==> Consul agent running!
           Version: 'v1.0.2'
           Node ID: 'dadca69a-7be6-604d-a85b-949cf55c6b2d'
         Node name: 'ee333f01072e'
        Datacenter: 'dc1' (Segment: '<all>')
            Server: true (Bootstrap: true)
       Client Addr: [0.0.0.0] (HTTP: 8500, HTTPS: -1, DNS: 8600)
      Cluster Addr: 172.19.0.2 (LAN: 8301, WAN: 8302)
           Encrypt: Gossip: false, TLS-Outgoing: false, TLS-Incoming: false

==> Log data will now stream in as it occurs:

    2018/01/06 02:51:12 [INFO] raft: Initial configuration (index=1): [{Suffrage:Voter ID:dadca69a-7be6-604d-a85b-949cf55c6b2d Address:172.19.0.2:8300}]
    2018/01/06 02:51:12 [INFO] serf: EventMemberJoin: ee333f01072e.dc1 172.17.8.150
    2018/01/06 02:51:12 [INFO] serf: EventMemberJoin: ee333f01072e 172.19.0.2
    2018/01/06 02:51:12 [INFO] agent: Started DNS server 0.0.0.0:8600 (udp)
    2018/01/06 02:51:12 [INFO] raft: Node at 172.19.0.2:8300 [Follower] entering Follower state (Leader: "")
    2018/01/06 02:51:12 [INFO] consul: Adding LAN server ee333f01072e (Addr: tcp/172.19.0.2:8300) (DC: dc1)
    2018/01/06 02:51:12 [INFO] consul: Handled member-join event for server "ee333f01072e.dc1" in area "wan"
    2018/01/06 02:51:12 [INFO] agent: Started DNS server 0.0.0.0:8600 (tcp)
    2018/01/06 02:51:12 [INFO] agent: Started HTTP server on [::]:8500 (tcp)
    2018/01/06 02:51:12 [INFO] agent: started state syncer
    2018/01/06 02:51:13 [INFO] serf: EventMemberJoin: 2ea49991d384 172.19.0.3
    2018/01/06 02:51:13 [INFO] consul: Adding LAN server 2ea49991d384 (Addr: tcp/172.19.0.3:8300) (DC: dc1)
    2018/01/06 02:51:13 [INFO] serf: EventMemberJoin: 2ea49991d384.dc1 172.19.0.3
    2018/01/06 02:51:13 [INFO] consul: Handled member-join event for server "2ea49991d384.dc1" in area "wan"
    2018/01/06 02:51:19 [WARN] raft: Heartbeat timeout from "" reached, starting election
    2018/01/06 02:51:19 [INFO] raft: Node at 172.19.0.2:8300 [Candidate] entering Candidate state in term 2
    2018/01/06 02:51:19 [INFO] raft: Election won. Tally: 1
    2018/01/06 02:51:19 [INFO] raft: Node at 172.19.0.2:8300 [Leader] entering Leader state
    2018/01/06 02:51:19 [INFO] consul: cluster leadership acquired
    2018/01/06 02:51:19 [INFO] consul: New leader elected: ee333f01072e
    2018/01/06 02:51:19 [INFO] agent: Synced node info
    2018/01/06 02:51:19 [INFO] raft: Updating configuration with AddNonvoter (cfea1ebd-c649-9e09-9cbd-aa639168ba0a, 172.19.0.3:8300) to [{Suffrage:Voter ID:dadca69a-7be6-604d-a85b-949cf55c6b2d Address:172.19.0.2:8300} {Suffrage:Nonvoter ID:cfea1ebd-c649-9e09-9cbd-aa639168ba0a Address:172.19.0.3:8300}]
    2018/01/06 02:51:19 [INFO] raft: Added peer cfea1ebd-c649-9e09-9cbd-aa639168ba0a, starting replication
    2018/01/06 02:51:19 [INFO] consul: member '2ea49991d384' joined, marking health alive
    2018/01/06 02:51:19 [WARN] raft: AppendEntries to {Nonvoter cfea1ebd-c649-9e09-9cbd-aa639168ba0a 172.19.0.3:8300} rejected, sending older logs (next: 1)
    2018/01/06 02:51:19 [INFO] raft: pipelining replication to peer {Nonvoter cfea1ebd-c649-9e09-9cbd-aa639168ba0a 172.19.0.3:8300}
    2018/01/06 02:51:19 [INFO] consul: member 'ee333f01072e' joined, marking health alive
    2018/01/06 02:51:39 [INFO] autopilot: Promoting Server (ID: "cfea1ebd-c649-9e09-9cbd-aa639168ba0a" Address: "172.19.0.3:8300") to voter
    2018/01/06 02:51:39 [INFO] raft: Updating configuration with AddStaging (cfea1ebd-c649-9e09-9cbd-aa639168ba0a, 172.19.0.3:8300) to [{Suffrage:Voter ID:dadca69a-7be6-604d-a85b-949cf55c6b2d Address:172.19.0.2:8300} {Suffrage:Voter ID:cfea1ebd-c649-9e09-9cbd-aa639168ba0a Address:172.19.0.3:8300}]
    2018/01/06 02:51:51 [INFO] serf: EventMemberJoin: 1af93f3512b4.dc2 172.17.8.151
    2018/01/06 02:51:51 [INFO] consul: Handled member-join event for server "1af93f3512b4.dc2" in area "wan"
    2018/01/06 02:52:07 [WARN] memberlist: Was able to connect to 1af93f3512b4.dc2 but other probes failed, network may be misconfigured
    2018/01/06 02:52:12 [WARN] memberlist: Was able to connect to 1af93f3512b4.dc2 but other probes failed, network may be misconfigured
    2018/01/06 02:52:22 [WARN] memberlist: Was able to connect to 1af93f3512b4.dc2 but other probes failed, network may be misconfigured
    2018/01/06 02:52:32 [WARN] memberlist: Was able to connect to 1af93f3512b4.dc2 but other probes failed, network may be misconfigured
    2018/01/06 02:52:42 [WARN] memberlist: Was able to connect to 1af93f3512b4.dc2 but other probes failed, network may be misconfigured
    2018/01/06 02:52:52 [WARN] memberlist: Was able to connect to 1af93f3512b4.dc2 but other probes failed, network may be misconfigured
```
Sorry for the false claim.

**Comment by slackpad** [comment]
No worries - glad we figured that out. Opening up 8302/udp should fix things!
